{{- if .Values.ingress.createCertificate -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{.Values.ingress.host}}
  labels:
  {{- include "raoa.labels" . | nindent 4 }}
spec:
  secretName: {{ include "raoa.tls.name" .}}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: {{.Values.ingress.host}}
  dnsNames:
    - {{.Values.ingress.host}}
  issuerRef:
  {{- toYaml .Values.ingress.issuerRef | nindent 4 -}}
  {{- end -}}
