kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "raoa.fullname" . }}-image-processor
  labels:
    {{- include "raoa.labels" . | nindent 4 }}
data:
  {{ include "raoa.common.config" . | nindent 2}}
  spring.kafka.bootstrap-servers: {{ include "raoa.fullname" . }}-kafka:9092
