apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: {{ include "raoa.fullname" . }}
spec:
  version: 7.6.0
  updateStrategy:
    changeBudget:
      maxSurge: 3
      maxUnavailable: 1
  nodeSets:
    - name: temp
      count: {{.Values.data.elasticsearch.nodeCount}}
      podTemplate:
        spec:
          volumes:
            - name: elasticsearch-data
              emptyDir: {}
      config:
        node.master: true
        node.data: true
        node.ingest: true
