apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: {{ include "raoa.fullname" . }}
spec:
  version: 7.2.0
  nodeSets:
    - name: raoa
      count: {{.Values.data.elasticsearch.nodeCount}}
      config:
        node.master: true
        node.data: true
        node.ingest: true
