apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: {{ include "raoa.fullname" . }}
spec:
  version: 7.2.0
  nodes:
    - nodeCount: {{.Values.data.elasticsearch.nodeCount}}
      volumeClaimTemplates:
        - metadata:
          name: {{ include "raoa.fullname" . }}-el-data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      config:
        node.master: true
        node.data: true
        node.ingest: true
