apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "raoa.name" .}}-read-secrets-rb
  labels:
    {{- include "raoa.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "raoa.serviceAccountName" . }}
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
