apiVersion: v1
kind: Service
metadata:
  name: {{ include "raoa.fullname" . }}-img-proc
  labels:
    {{- include "raoa.labels" . | nindent 4 }}
    role: img-proc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "raoa.imageProcessorSelectorLabels" . | nindent 4 }}
