apiVersion: v1
kind: Service
metadata:
  name: {{ include "raoa.fullname" . }}-cdr-mgmt
  labels:
    {{- include "raoa.labels" . | nindent 4 }}
    role: mgmt
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.managementPort }}
      targetPort: management
      protocol: TCP
      name: mgmt
  selector:
    {{- include "raoa.coordinatorSelectorLabels" . | nindent 4 }}
