spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            raoa-thumbnailer:
              - uri: http://thumbnailer.lkw.teamkoenig.ch/
    kubernetes:
      enabled: false
  security:
    user:
      name: user
      password: 1234
raoa:
  media: /media
  repository: /tmp/photos
  viewer:
    cache-dir: /tmp/cache

