spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            raoa-thumbnailer:
              - uri: http://localhost:8081/
    kubernetes:
      enabled: false
      config:
        enabled: false
        enable-api: false
      discovery:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
security:
  oauth2:
    resource:
      jwk:
        key-set-uri: https://www.googleapis.com/oauth2/v3/certs
raoa:
  media: /media
  repository: /tmp/photos
  viewer:
    cache-dir: /tmp/raoa/cache
    data-dir: /tmp/raoa/data
  metadata-cache: /tmp/raoa/metadataCache

