[serve]
port = 4200
[[proxy]]
backend = "https://photos.berg-turbenthal.ch/graphql"
[[proxy]]
backend = "https://photos.berg-turbenthal.ch/config"
[[proxy]]
backend = "https://photos.berg-turbenthal.ch/rest/"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "sleep 4"]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "clear"]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "cd node && npm install && npm run build"]

[watch]
watch = ["src", "index.html", "node/main.js", "node/package.json", "node/src"]

[build]
target = "index.html"
dist = "target/dist"
filehash = true
public_url = "/"
