[serve]
port = 4200
[[proxy]]
backend = "https://photos.lkw.teamkoenig.ch/graphql"
[[proxy]]
backend = "https://photos.lkw.teamkoenig.ch/config"
[[proxy]]
backend = "https://photos.lkw.teamkoenig.ch/rest/"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "sleep 4"]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "clear"]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "cd node && npm install"]

[watch]
watch = ["src", "index.html", "local.css"]

[build]
target = "index.html"
dist = "dist"
filehash = true
public_url = "/"
