kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "raoa.fullname" . }}-coordinator
  labels:
    {{- include "raoa.labels" . | nindent 4 }}
data:
  {{ include "raoa.common.config" . | nindent 2}}
  {{ toYaml .Values.coordinatorSettings | nindent 2 }}
  raoa.coordinator.imageProcessorUrl: discovery://{{ include "raoa.fullname" . }}-img-proc
