kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "raoa.fullname" . }}-init-script
  labels:
  {{- include "raoa.labels" . | nindent 4 }}
data:
  init: |
    cd /data
    test -d .meta.git || git init --bare .meta.git
    chown -R $TARGET_USER:$TARGET_GROUP .
    cd /cache
    chown -R $TARGET_USER:$TARGET_GROUP .
