apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "raoa.fullname" . }}-coordinator
  labels:
  {{- include "raoa.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
  {{- include "raoa.coordinatorSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "raoa.coordinatorSelectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-coordinator.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "raoa.serviceAccountName" . }}
      {{- if .Values.priorityClass.coordinator }}
      priorityClassName: {{ .Values.priorityClass.coordinator }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: clean-repos
          image: library/busybox:1.32.0
          volumeMounts:
            - mountPath: /data
              name: data
          command:
            - sh
            - -c
            - find /data -name .probe-* -print0 | xargs -0 -n 1 -r rm
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.coordinatorRepository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort}}
            - name: management
              containerPort: {{ .Values.managementPort}}
            {{ if .Values.debug.enabled}}
            - name: debug
              containerPort: {{ .Values.debug.port}}
          {{ end}}
          readinessProbe:
            httpGet:
              port: {{ .Values.managementPort}}
              path: /actuator/health
            initialDelaySeconds: 10
            failureThreshold: 30
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: {{ .Values.managementPort}}
              path: /actuator/health
            initialDelaySeconds: 90
            failureThreshold: 5
            periodSeconds: 5
          env:
            {{ if .Values.debug.enabled}}
            - name: JAVA_TOOL_OPTIONS
              value: {{ printf "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=localhost:%i" .Values.debug.port | quote}}
            {{ end}}
            - name: SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "raoa.fullname" . }}-es-elastic-user
                  key: elastic
            - name: SPRING_ELASTICSEARCH_REST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "raoa.fullname" . }}-es-elastic-user
                  key: elastic
            - name: SPRING_APPLICATION_NAME
              value: {{ include "raoa.fullname" . }}-coordinator
          volumeMounts:
            - mountPath: /cache
              name: shared-cache
            - mountPath: /data
              name: data
            - mountPath: /dumps
              name: dumps
          resources:
            {{- toYaml .Values.coordinatorResources | nindent 12 }}
      {{ with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{ end }}
      volumes:
        - name: data
          {{- include "raoa.dataVolume" . | nindent 10 }}
        - name: shared-cache
          {{- include "raoa.cacheVolume" . | nindent 10 }}
        - name: dumps
          emptyDir: {}
