apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "raoa.fullname" . }}
spec:
  version: 7.14.0
  updateStrategy:
    changeBudget:
      maxSurge: 3
      maxUnavailable: 1
  nodeSets:
    - name: data
      count: {{.Values.data.elasticsearch.nodeCount}}
      config:
        xpack.ml.enabled: false
      podTemplate:
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
          containers:
            - name: elasticsearch
              securityContext:
                capabilities:
                  add: ["SYS_CHROOT"]
          {{ if .Values.data.elasticsearch.volumesOverride }}
          volumes:
            {{- toYaml .Values.data.elasticsearch.volumes | nindent 12 }}
          {{ end }}
