apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "raoa.fullname" . }}
spec:
  version: 8.19.3
  updateStrategy:
    changeBudget:
      maxSurge: 3
      maxUnavailable: 1
  nodeSets:
    - name: {{.Values.data.elasticsearch.nodeSetName}}
      count: {{.Values.data.elasticsearch.nodeCount}}
      config:
        xpack.ml.enabled: false
      podTemplate:
        spec:
          {{ if .Values.data.elasticsearch.setSysctl}}
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
          {{ end }}
          containers:
            - name: elasticsearch
              securityContext:
                capabilities:
                  add: [ "SYS_CHROOT" ]
              resources:
                {{- toYaml .Values.data.elasticsearch.resources | nindent 16 }}
      {{ if .Values.data.elasticsearch.volumesOverride }}
      volumeClaimTemplates:
        {{- toYaml .Values.data.elasticsearch.volumes | nindent 8 }}
      {{ end }}
