apiVersion: batch/v1
kind: Job
metadata:
  name: init-git
  labels:
  {{- include "raoa.labels" . | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "raoa.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-repack
          image: "{{ .Values.repack.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TARGET_USER
              value: {{.Values.securityContext.runAsUser | quote}}
            - name: TARGET_GROUP
              value: {{.Values.securityContext.runAsGroup | quote}}
          command:
            - /bin/sh
            - /script/init
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /script
              name: script
            - mountPath: /cache
              name: shared-cache
      volumes:
        - name: data
          {{- include "raoa.dataVolume" . | nindent 10 }}
        - name: shared-cache
          {{- include "raoa.cacheVolume" . | nindent 10 }}
        - name: script
          configMap:
            name: {{ include "raoa.fullname" . }}-init-script
      restartPolicy: OnFailure

