apiVersion: batch/v1
kind: Job
metadata:
  name: init-git
  labels:
  {{- include "raoa.labels" . | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "raoa.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-repack
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.repack.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - /script/init
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /script
              name: script
      volumes:
        - name: data
          {{- include "raoa.dataVolume" . | nindent 10 }}
        - name: script
          configMap:
            name: {{ include "raoa.fullname" . }}-init-script
      restartPolicy: OnFailure

