{{- if .Values.data.cache.override -}}
{{- else -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "raoa.name" .}}-cache
  labels:
  {{- include "raoa.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.data.cache.size}}
{{- end -}}
