apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-coordinator
  labels:
  {{- include "raoa.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list","update","create","delete"]
