{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "raoa.serviceAccountName" . }}
  labels:
    {{- include "raoa.labels" . | nindent 4 }}
{{- end -}}
