{{- if .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "raoa.fullname" . }}
  labels:
    {{- include "raoa.labels" . | nindent 4 }}
    release: monitoring
spec:
  selector:
    matchLabels:
      {{- include "raoa.selectorLabels" . | nindent 6 }}
      role: mgmt
  endpoints:
    - port: mgmt
      path: '/actuator/prometheus'
      interval: 10s
      honorLabels: true
{{- end -}}
